# Generated by Django 2.2.2 on 2019-06-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='total_book_written',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='student name', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('book_took', models.ForeignKey(help_text='Book Took', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Book')),
            ],
        ),
    ]
