# Generated by Django 2.2.2 on 2019-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190620_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issue'),
        ),
    ]
