# Generated by Django 2.2.2 on 2019-06-20 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='senddate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 6, 20, 12, 33, 22, 393734), verbose_name='Send after'),
        ),
        migrations.AddField(
            model_name='student',
            name='toaddress',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True, verbose_name='To (Additional address or addresses)'),
        ),
    ]
