# Generated by Django 2.2.2 on 2019-06-22 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190621_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='senddate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 6, 22, 14, 52, 46, 872275), verbose_name='Send after'),
        ),
    ]
